import "~/styles/globals.css";

import Navbar from "./_components/navbar";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "An Blog Website",
  description: "A Blog Platform Generated by create-t3-app, by ngk-t",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <div className="fixed top-0 z-40 w-full h-14 bg-white/25 backdrop-blur-md"></div>
          <Navbar />
          <main className="flex-grow">
          {children}
          </main>
        </TRPCReactProvider>

        {/* Footer */}
        <footer className="w-full h-52 bg-white mt-24 py-10 pr-16 text-right">
        </footer>
      </body>
    </html>
  );
}
