import "~/styles/globals.css";

import Navbar from "./_components/navbar";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "An Blog Website",
  description: "A Blog Platform Generated by create-t3-app, by ngk-t",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <Navbar />
          {children}
        </TRPCReactProvider>

        {/* Footer */}
        <div className="w-full h-52 bg-neutral-200 py-10 pr-16 text-right">
          <p className="font-bold text-md my-6">© (not copyright-ed) An blog website</p>
          <p className="text-sm my-2">created by Khoi Truong</p>
          <p className="text-sm">truong.hnkhoi@outlook.com</p>
        </div>
      </body>
    </html>
  );
}
